CREATE TABLE "hearsay-hub_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "hearsay-hub_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "hearsay-hub_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hearsay-hub_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hearsay-hub_quote_vote" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hearsay-hub_quote_vote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quoteId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"voteType" varchar(10) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "quote_vote_unique_user_quote" UNIQUE("quoteId","userId")
);
--> statement-breakpoint
CREATE TABLE "hearsay-hub_quote" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hearsay-hub_quote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content" text NOT NULL,
	"context" text,
	"quoteDate" date,
	"quoteDatePrecision" varchar(20) DEFAULT 'unknown',
	"speakerId" integer NOT NULL,
	"submittedById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hearsay-hub_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hearsay-hub_speaker" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hearsay-hub_speaker_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"createdById" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hearsay-hub_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"role" varchar(50) DEFAULT 'USER'
);
--> statement-breakpoint
CREATE TABLE "hearsay-hub_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "hearsay-hub_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "hearsay-hub_account" ADD CONSTRAINT "hearsay-hub_account_userId_hearsay-hub_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hearsay-hub_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hearsay-hub_post" ADD CONSTRAINT "hearsay-hub_post_createdById_hearsay-hub_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."hearsay-hub_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hearsay-hub_quote_vote" ADD CONSTRAINT "hearsay-hub_quote_vote_quoteId_hearsay-hub_quote_id_fk" FOREIGN KEY ("quoteId") REFERENCES "public"."hearsay-hub_quote"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hearsay-hub_quote_vote" ADD CONSTRAINT "hearsay-hub_quote_vote_userId_hearsay-hub_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hearsay-hub_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hearsay-hub_quote" ADD CONSTRAINT "hearsay-hub_quote_speakerId_hearsay-hub_speaker_id_fk" FOREIGN KEY ("speakerId") REFERENCES "public"."hearsay-hub_speaker"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hearsay-hub_quote" ADD CONSTRAINT "hearsay-hub_quote_submittedById_hearsay-hub_user_id_fk" FOREIGN KEY ("submittedById") REFERENCES "public"."hearsay-hub_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hearsay-hub_session" ADD CONSTRAINT "hearsay-hub_session_userId_hearsay-hub_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hearsay-hub_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hearsay-hub_speaker" ADD CONSTRAINT "hearsay-hub_speaker_createdById_hearsay-hub_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."hearsay-hub_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "hearsay-hub_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "hearsay-hub_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "hearsay-hub_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "quote_vote_quote_idx" ON "hearsay-hub_quote_vote" USING btree ("quoteId");--> statement-breakpoint
CREATE INDEX "quote_vote_user_idx" ON "hearsay-hub_quote_vote" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "quote_vote_type_idx" ON "hearsay-hub_quote_vote" USING btree ("voteType");--> statement-breakpoint
CREATE INDEX "quote_speaker_idx" ON "hearsay-hub_quote" USING btree ("speakerId");--> statement-breakpoint
CREATE INDEX "quote_submitted_by_idx" ON "hearsay-hub_quote" USING btree ("submittedById");--> statement-breakpoint
CREATE INDEX "quote_created_at_idx" ON "hearsay-hub_quote" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "hearsay-hub_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "speaker_name_idx" ON "hearsay-hub_speaker" USING btree ("name");--> statement-breakpoint
CREATE INDEX "speaker_created_by_idx" ON "hearsay-hub_speaker" USING btree ("createdById");