CREATE TABLE "hearsay-hub_quote_speaker" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hearsay-hub_quote_speaker_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quoteId" integer NOT NULL,
	"speakerId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "quote_speaker_unique" UNIQUE("quoteId","speakerId")
);
--> statement-breakpoint
ALTER TABLE "hearsay-hub_quote_speaker" ADD CONSTRAINT "hearsay-hub_quote_speaker_quoteId_hearsay-hub_quote_id_fk" FOREIGN KEY ("quoteId") REFERENCES "public"."hearsay-hub_quote"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hearsay-hub_quote_speaker" ADD CONSTRAINT "hearsay-hub_quote_speaker_speakerId_hearsay-hub_speaker_id_fk" FOREIGN KEY ("speakerId") REFERENCES "public"."hearsay-hub_speaker"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "quote_speaker_quote_idx" ON "hearsay-hub_quote_speaker" USING btree ("quoteId");--> statement-breakpoint
CREATE INDEX "quote_speaker_speaker_idx" ON "hearsay-hub_quote_speaker" USING btree ("speakerId");--> statement-breakpoint

-- Migrate existing quote-speaker relationships from the quotes table to the junction table
-- This preserves all legacy quotes with their original speakers
INSERT INTO "hearsay-hub_quote_speaker" ("quoteId", "speakerId", "createdAt")
SELECT "id", "speakerId", "createdAt" 
FROM "hearsay-hub_quote" 
WHERE "speakerId" IS NOT NULL;
--> statement-breakpoint

-- Now safely remove the old foreign key constraint and column
ALTER TABLE "hearsay-hub_quote" DROP CONSTRAINT "hearsay-hub_quote_speakerId_hearsay-hub_speaker_id_fk";
--> statement-breakpoint
DROP INDEX "quote_speaker_idx";--> statement-breakpoint
ALTER TABLE "hearsay-hub_quote" DROP COLUMN "speakerId";